Repository SatelliteQE/airgun, pull requests merged in 2018-10, with the labels that each got.

#202 Implement Discovered Hosts Entity
  airgun/entities/discoveredhosts.py
  airgun/session.py
  airgun/views/discoveredhosts.py
Labels: entity

#212 Fix Discovery Rules entity
  airgun/entities/discoveryrule.py
  airgun/views/discoveryrule.py
Labels: bug

#211 Implemented helpers and views for content view filter entity
  airgun/entities/contentview.py
  airgun/entities/contentviewfilter.py
  airgun/session.py
  airgun/views/common.py
  airgun/views/contentview.py
  airgun/views/contentviewfilter.py
  airgun/widgets.py
Labels: entity, review, view

#219 Implemented Bookmarks entity
  airgun/entities/base.py
  airgun/entities/bookmark.py
  airgun/session.py
  airgun/views/bookmark.py
  airgun/views/common.py
  airgun/widgets.py
Labels: entity, view

#226 Fix AddRemoveSubscriptionsView
  airgun/views/common.py
  airgun/views/contentviewfilter.py
Labels: bug, high

#227 Fix subscription waiter helper
  airgun/entities/subscription.py
Labels: bug
