Repository SatelliteQE/airgun, pull requests merged in 2020-12, with the labels that each got.

#540 Update the virt-who view as the http proxy option has been updated
  airgun/views/virtwho_configure.py
Labels: Automation failure

#534 Add the ability to create a session for a different satellite
  airgun/browser.py
  airgun/session.py
Labels: enhancement

#543 Implement "Register Host" page
  airgun/entities/host.py
  airgun/views/host.py
Labels: entity, view
