Repository SatelliteQE/airgun, pull requests merged in 2021-06, with the labels that each got.

#574 Use patternfly4 context selector for org/location dropdown
  airgun/widgets.py
Labels: Automation failure, PF4, critical

#579 Add support for configure_cloud_connector and sync_inventory_status
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_inventory.py
Labels: enhancement, view

#575 Fix Infrastructure component locators for 6.10
  airgun/views/computeprofile.py
  airgun/views/computeresource.py
  airgun/views/domain.py
  airgun/views/http_proxy.py
  airgun/views/subnet.py
Labels: Automation failure
