Repository SatelliteQE/airgun, pull requests merged in 2021-05, with the labels that each got.

#571 Create SatTablePagination class for use within SatTable
  airgun/widgets.py
Labels: Automation failure

#572 Don't overwrite FlashMessages methods
  airgun/widgets.py
Labels: enhancement

#568 Update rh_cloud inventory page code to support pf4
  airgun/browser.py
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_inventory.py
  airgun/widgets.py
  setup.py
Labels: view

#577 Fix browser issue for get_file_content
  airgun/browser.py
Labels: bug
