Repository SatelliteQE/airgun, pull requests merged in 2021-08, with the labels that each got.

#601 fixing the host-group create button locator mix-up
  airgun/entities/hostgroup.py
  airgun/views/hostgroup.py
Labels: locator

#602 [Cherry-pick]Added flash data cleanup before logout
  airgun/entities/login.py
  airgun/views/login.py
Labels: Automation failure, locator

#603 Bookmarks: check if submit button is enabled
  airgun/entities/base.py
  airgun/views/common.py
Labels: Automation failure

#604 Added permission denied entity in settings module
  airgun/entities/settings.py
  airgun/views/common.py
Labels: Automation failure

#605 [Cherry-pick] Added permission denied entity in settings module
  airgun/entities/settings.py
  airgun/views/common.py
Labels: Automation failure

#606 Remove SyspurposeBulkActionView confirm step
  airgun/entities/contenthost.py
  airgun/views/contenthost.py
Labels: Automation failure

#610 Update locators for dashboard tests
  airgun/views/dashboard.py
  airgun/views/task.py
Labels: critical, Automation failure
