Repository SatelliteQE/airgun, pull requests merged in 2021-07, with the labels that each got.

#582 Update current_user to OUIA Dropdown
  airgun/views/common.py
Labels: PF4

#580 Fixes for some UI CR VMware tests
  airgun/entities/computeresource.py
  airgun/views/computeresource.py
  airgun/widgets.py
Labels: Automation failure

#590 Added flash data cleanup before logout
  airgun/entities/login.py
  airgun/views/login.py
Labels: Automation failure, locator

#585 Fix for a report template test
  airgun/entities/report_template.py
  airgun/views/report_template.py
Labels: Automation failure, bug

#583 Removing all elements of puppet modules from view and entities file
  airgun/entities/contentview.py
  airgun/views/contentview.py
Labels: PF4, entity, view

#593 GHA for airgun
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: enhancement

#594 add views for ansible collection repo
  airgun/views/repository.py
Labels: view

#588 Changes needed to fix templatesync tests
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
  airgun/views/sync_templates.py
Labels: Automation failure, locator

#576 Add support for Red Hat Insights page
  airgun/entities/cloud_insights.py
  airgun/session.py
  airgun/views/cloud_insights.py
  airgun/widgets.py
Labels: PF4, enhancement, view

#598 Add docs build to GHA and remove travis config
  .github/workflows/pull_request.yml
  .travis.yml
Labels: enhancement
