Repository SatelliteQE/airgun, pull requests merged in 2021-11, with the labels that each got.

#633 update pre commit
  .pre-commit-config.yaml
  airgun/entities/product.py
  airgun/views/cloud_insights.py
  airgun/views/subscription.py
  airgun/views/sync_status.py
  airgun/widgets.py
Labels: high

#634 update pre-commit for 6.9.z
  .pre-commit-config.yaml
  airgun/entities/product.py
  airgun/entities/repository.py
  airgun/views/subscription.py
  airgun/views/sync_status.py
  airgun/widgets.py
Labels: high

#632 test fix, Text element changed to TextInput
  airgun/views/host.py
Labels: bug, Automation failure

#636 Fix deleting a repo entity
  airgun/entities/repository.py
Labels: entity, Automation failure
