Repository SatelliteQE/airgun, pull requests merged in 2022-05, with the labels that each got.

#694 rhcloud-UI fix for test cases failing with locator error
  airgun/views/cloud_inventory.py
Labels: locator

#696 new host details dropdown locator fix
  airgun/views/host_new.py
Labels: Automation failure, locator

#704 fixed the squash issue in handling the alerts
  airgun/browser.py
Labels: bug, critical, Automation failure
