Repository SatelliteQE/airgun, pull requests merged in 2022-07, with the labels that each got.

#722 updated the checkbox checking using javascript
  airgun/entities/product.py
  airgun/views/product.py
Labels: bug, Automation failure

#726 Remove preimport_check and move functionality
  airgun/entities/ansible_role.py
Labels: enhancement

#721 adding new functionality for verify checksum
  airgun/entities/product.py
  airgun/views/product.py
Labels: enhancement, entity, view

#724 Skipping ensure_page_safe on timeout.
  airgun/browser.py
  airgun/entities/computeresource.py
Labels: enhancement, Automation failure

#723 Adding Webhooks CRUD
  airgun/entities/webhook.py
  airgun/session.py
  airgun/views/webhook.py
  airgun/widgets.py
Labels: entity

#727 [UI] -Test fixes for rh_cloud inventory
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_inventory.py
Labels: Automation failure

#729 Click in ignored ensuresafepage. Set low timeout.
  airgun/browser.py
  airgun/entities/computeresource.py
Labels: bug, Automation failure

#730 fix locators for hardware models tests
  airgun/entities/hardware_model.py
  airgun/views/hardware_model.py
  airgun/views/host.py
  airgun/widgets.py
Labels: view, Automation failure, locator
