Repository SatelliteQE/airgun, pull requests merged in 2022-09, with the labels that each got.

#742 Add rex related views and entities for new host details
  airgun/entities/host_new.py
  airgun/views/host_new.py
  airgun/widgets.py
Labels: PF4, 6.12, No-CherryPick

#744 Replace find_element_by_xpath with find_element
  airgun/widgets.py
Labels: Automation failure, CherryPick

#745 Add support for container repo discovery
  airgun/views/product.py
Labels: No-CherryPick

#743 Ensure cockpit page is safe before locating elements
  airgun/entities/host.py
Labels: entity, Automation failure, CherryPick

#748 updating the airgun autocherrypick n-1 version as robottelo
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#756 Recent audits and jobs as table
  airgun/views/host_new.py
Labels: 6.12, No-CherryPick

#758 Rename column in puppet class table
  airgun/entities/puppet_class.py
  airgun/views/puppet_class.py
Labels: Automation failure, 6.12, No-CherryPick

#757 fixing the locator for logout page rhsso
  airgun/views/rhsso_login.py
Labels: CherryPick

#755 Add static OUIA id for close button in confirmation dialog
  airgun/widgets.py
Labels: 6.12, No-CherryPick

#754 Locator fix for errata
  airgun/views/contenthost.py
Labels: view, locator, CherryPick

#761 Fixing new Webhook button
  airgun/entities/webhook.py
  airgun/views/webhook.py
Labels: Automation failure, No-CherryPick

#762 Remove publish via http field since it's no longer valid
  airgun/views/repository.py
Labels: view, CherryPick

#749 Create cv and search for new CV UI
  airgun/entities/contentview_new.py
  airgun/session.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: entity, view, PF4, 6.12, No-CherryPick

#763 Missing delete confirmation function
  airgun/entities/lifecycleenvironment.py
Labels: entity, view, Automation failure, No-CherryPick

#767 Updated locator for Text field in Settings
  airgun/widgets.py
Labels: CherryPick
