Repository SatelliteQE/airgun, pull requests merged in 2022-10, with the labels that each got.

#766 Fix OUIA IDs in hosts
  airgun/views/host.py
  airgun/views/host_new.py
Labels: 6.12, No-CherryPick

#773 added the support for the clone host-group
  airgun/entities/hostgroup.py
Labels: CherryPick

#771 Uncommenting select_all_hits
  airgun/entities/cloud_insights.py
Labels: entity, CherryPick

#778 Fix minor typo
  airgun/views/provisioning_template.py
Labels: No-CherryPick
