Repository SatelliteQE/airgun, pull requests merged in 2022-08, with the labels that each got.

#731 Fix tasks pagination
  airgun/entities/task.py
  airgun/views/task.py
Labels: PF4, 6.12

#732 AutoCherrypick GHAs
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/required_labels.yml
Labels: CherryPick

#725 Fixing PF4ConfirmationDialog
  airgun/widgets.py
Labels: locator, 6.12

#736 Fix locator for column_value in PopOverWidget
  airgun/widgets.py
Labels: No-CherryPick

#735 use new host UI by default
  airgun/entities/host.py
Labels: 6.12, No-CherryPick

#738 Fixing locator for login page footer
  airgun/views/login.py
Labels: locator, CherryPick

#720 Add content tab to new host UI
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: view, PF4, 6.12, No-CherryPick
