Repository SatelliteQE/airgun, pull requests merged in 2022-11, with the labels that each got.

#781 Change status id to static one
  airgun/views/host_new.py
Labels: Automation failure, 6.12.z, No-CherryPick

#780 Aligning ACP GHA with Robottelo
  .github/auto_assign.yml
  .github/workflows/auto_assignment.yaml
  .github/workflows/auto_cherry_pick.yml
Labels: critical, CherryPick, Framework Changes

#785 [6.11.z] Switch classifiers from a tuple to a list
  .pre-commit-config.yaml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.11.z

#775 Fixes for Robottelo Role/Variable UI tests
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
  airgun/widgets.py
Labels: CherryPick

#770 Add repository sets to new host details UI
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: 6.12.z, No-CherryPick
