Repository SatelliteQE/airgun, pull requests merged in 2022-06, with the labels that each got.

#711 fixed the bookmark search in airgun
  airgun/widgets.py
Labels: bug, Automation failure, PF4, locator

#712 Fixing DiscoveryPlugin failures
  airgun/entities/discoveredhosts.py
  airgun/entities/discoveryrule.py
  airgun/views/discoveredhosts.py
  airgun/views/discoveryrule.py
Labels: Automation failure

#715 Close action dropdown after reading
  airgun/widgets.py
Labels: bug, Automation failure
