Repository SatelliteQE/airgun, pull requests merged in 2023-02, with the labels that each got.

#804 [6.11.z] adding auto merge in airgun
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.11.z

#806 [6.12.z] adding auto merge in airgun
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#805 [6.13.z] adding auto merge in airgun
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#808 Fix configure_cloud_connector method
  airgun/entities/cloud_inventory.py
Labels: CherryPick, 6.13.z

#809 [6.13.z] Fix configure_cloud_connector method
  airgun/entities/cloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#802 Updated Activation keys field location on global registration page
  airgun/views/host.py
Labels: CherryPick, 6.13.z

#810 [6.13.z] Updated Activation keys field location on global registration page
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#807 Removing email project_id cert_path based on the new GCE-CR feature
  airgun/views/computeresource.py
Labels: view, locator, CherryPick, 6.13.z

#811 Fix locator for hosts table
  airgun/views/host.py
Labels: Automation failure, locator, CherryPick, 6.13.z

#803 ahv_internal_debug virt-who config support
  airgun/views/virtwho_configure.py
Labels: No-CherryPick

#813 [6.13.z] Fix locator for hosts table
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#717 New Host UI Ansible Work
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: view, PF4, CherryPick
