Repository SatelliteQE/airgun, pull requests merged in 2023-10, with the labels that each got.

#995 [6.14.z] subscription page failure fix
  airgun/entities/subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#994 [6.13.z] subscription page failure fix
  airgun/entities/subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#993 [6.14.z] Add PF4 versions of MultiSelect and FilteredDropdown. Use them in Filters.
  airgun/entities/filter.py
  airgun/views/filter.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#996 Add catalog info for backstage
  catalog-info.yaml
Labels: No-CherryPick

#976 fixing the memory issue in auto-cherry-pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#997 Fix bad table row locator
  airgun/views/activationkey.py
Labels: CherryPick, 6.14.z

#1000 ACS Stability issues fix
  airgun/entities/acs.py
Labels: CherryPick, 6.14.z

#1003 Update Activation Keys helper OUIA ID
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#1006 Add read() method for BaseMultiSelect widget
  airgun/widgets.py
Labels: 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z

#1004 [6.14.z] Update Activation Keys helper OUIA ID
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#948 CV Publish
  airgun/entities/contentview_new.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: CherryPick, 6.13.z, 6.14.z

#1005 Remove katello-agent from entities and views
  airgun/entities/contenthost.py
  airgun/entities/hostcollection.py
  airgun/views/contenthost.py
  airgun/views/hostcollection.py
Labels: entity, view, No-CherryPick, Stream

#999 Update the Container Image Tags page view
  airgun/views/containerimagetag.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#1012 [6.14.z] Update the Container Image Tags page view
  airgun/views/containerimagetag.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1007 [6.13.z] Add read() method for BaseMultiSelect widget
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1008 [6.14.z] Add read() method for BaseMultiSelect widget
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1009 [6.12.z] Add read() method for BaseMultiSelect widget
  airgun/widgets.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked
