Repository SatelliteQE/airgun, pull requests merged in 2023-03, with the labels that each got.

#814 Fix locator for content host table
  airgun/views/contenthost.py
Labels: locator, CherryPick, 6.13.z

#817 [6.13.z] Fix locator for content host table
  airgun/views/contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#816 Cherry-picking Ansible UI fixes
  airgun/entities/ansible_role.py
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
Labels: No-CherryPick, 6.13.z

#815 Cherry-picking Ansible UI fixes
  airgun/entities/ansible_role.py
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
Labels: entity, view, locator, CherryPick, 6.11.z

#824 Cherrypick New Host Ansible work
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick

#821 Updates to New Host UI Traces tab
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, 6.13.z

#825 [6.13.z] Updates to New Host UI Traces tab
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z
