Repository SatelliteQE/airgun, pull requests merged in 2023-04, with the labels that each got.

#819 new job-inv page
  airgun/views/common.py
  airgun/views/job_invocation.py
Labels: CherryPick, 6.13.z

#827 [6.13.z] new job-inv page
  airgun/views/common.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#829 [6.13.z] NewHostEntity::get_details() wait check added
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#820 New Host UI - Manage columns functions
  airgun/entities/host.py
  airgun/views/host.py
  airgun/views/host_new.py
Labels: CherryPick, 6.13.z

#831 [6.13.z] New Host UI - Manage columns functions
  airgun/entities/host.py
  airgun/views/host.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#822 View for multiple host tabs added
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: enhancement, entity, view, CherryPick, 6.13.z

#828 change locator for `Name` in `HostsView`
  airgun/views/host.py
Labels: CherryPick, 6.13.z

#830 Fix Pagination for Content Hosts
  airgun/views/contenthost.py
Labels: CherryPick, 6.13.z

#837 [cherry-pick] Fix configure_cloud_connector method
  airgun/entities/cloud_inventory.py
Labels: No-CherryPick
