Repository SatelliteQE/airgun, pull requests merged in 2023-09, with the labels that each got.

#951 pining the selenium version to 4.11.2
  setup.py
Labels: Automation failure, 6.12.z, CherryPick, 6.13.z, 6.14.z

#953 [6.14.z] pining the selenium version to 4.11.2
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#952 [6.12.z] pining the selenium version to 4.11.2
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#954 [6.13.z] pining the selenium version to 4.11.2
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#950 [6.14.z]: Add Legacy content host UI support #850
  airgun/entities/contenthost.py
Labels: CherryPick, 6.13.z

#963 [6.13.z]: Add Legacy content host UI support #850
  airgun/entities/contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#967 Scap contentview title fixed
  airgun/views/oscapcontent.py
Labels: Automation failure, locator, No-CherryPick, 6.14.z

#968 [6.13.z] Scap contentview title fixed
  airgun/views/oscapcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#964 adding the test name as metadata for searching in grid sessions
  airgun/browser.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#965 Fix clean button locator in PF4 search.
  airgun/widgets.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#974 [6.14.z] Fix clean button locator in PF4 search.
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#975 Removing auto release WF from non-master branches
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick, 6.14.z

#977 Enabling RedHat repositories enhanced
  airgun/entities/redhat_repository.py
Labels: entity, CherryPick, 6.14.z

#978 [6.14.z] Enabling RedHat repositories enhanced
  airgun/entities/redhat_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#966 add Host statues modal support
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#981 [6.13.z] add Host statues modal support
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, 6.13.z

#973 [6.14.z] adding the test name as metadata for searching in grid sessions
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#971 [6.13.z] adding the test name as metadata for searching in grid sessions
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#972 [6.12.z] adding the test name as metadata for searching in grid sessions
  airgun/browser.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#983 [6.14.z] fixed the diff between gha robottelo and airgun
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick

#986 [6.12.z] add Host statuses modal support (#966)
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: 6.12.z, No-CherryPick

#988 [6.14.z] add Host statuses modal support (#966)
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, 6.14.z

#979 Add PF4 versions of MultiSelect and FilteredDropdown. Use them in Filters.
  airgun/entities/filter.py
  airgun/views/filter.py
  airgun/widgets.py
Labels: CherryPick, 6.14.z
