Repository SatelliteQE/airgun, pull requests merged in 2023-12, with the labels that each got.

#1056 [6.15.z] eol banner
  airgun/entities/eol_banner.py
  airgun/session.py
  airgun/views/eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1058 [6.13.z] eol banner
  airgun/entities/eol_banner.py
  airgun/session.py
  airgun/views/eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1059 Add check to verify supported provisioning templates
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
Labels: 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1068 [6.15.z] Add error-msg class in ValidationErrors for settings
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1067 [6.14.z] Add error-msg class in ValidationErrors for settings
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1066 [6.13.z] Add error-msg class in ValidationErrors for settings
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1065 [6.12.z] Add error-msg class in ValidationErrors for settings
  airgun/widgets.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1060 [6.13.z] Add check to verify supported provisioning templates
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1062 [6.15.z] Add check to verify supported provisioning templates
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1061 [6.14.z] Add check to verify supported provisioning templates
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1063 [6.12.z] Add check to verify supported provisioning templates
  airgun/entities/provisioning_template.py
  airgun/views/provisioning_template.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1050 Added Satellite Capsule page coverage
  airgun/entities/capsule.py
  airgun/session.py
  airgun/views/capsule.py
  airgun/widgets.py
Labels: entity, view, CherryPick, 6.15.z

#1014 CV UI Filter Create/Delete/Edit
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: CherryPick, 6.13.z, 6.14.z

#1069 Remove LCE field from HostRegisterView
  airgun/views/host.py
Labels: CherryPick, 6.15.z

#1070 [6.15.z] Added Satellite Capsule page coverage
  airgun/entities/capsule.py
  airgun/session.py
  airgun/views/capsule.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1013 Added possibility to search for debian errata
  airgun/__init__.py
  airgun/entities/errata.py
  airgun/views/errata.py
Labels: CherryPick, 6.15.z

#1075 [6.15.z] Remove LCE field from HostRegisterView
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1079 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1080 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1081 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1015 Host Details Locator Cleanup
  airgun/views/host_new.py
Labels: locator, CherryPick, 6.13.z, 6.14.z

#1086 [6.15.z] Add some wait_displayed
  airgun/entities/capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1076 Search functionality for vertical navigation menu
  airgun/entities/base.py
  airgun/views/common.py
  airgun/widgets.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#1084 [6.14.z] Host Details Locator Cleanup
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1085 [6.13.z] Host Details Locator Cleanup
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1077 [6.15.z] Added possibility to search for debian errata
  airgun/__init__.py
  airgun/entities/errata.py
  airgun/views/errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1089 [6.15.z] Search functionality for vertical navigation menu
  airgun/entities/base.py
  airgun/views/common.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1090 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1092 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1091 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1093 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1087 Update get_register_command to reflect new mandatory fields
  airgun/entities/host.py
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#1094 [6.15.z] Update get_register_command to reflect new mandatory fields
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1095 Update get_register_command to reflect new mandatory fields
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, 6.14.z
