Repository SatelliteQE/airgun, pull requests merged in 2023-11, with the labels that each got.

#1016 enabled the pre-commit CI and remove pre-commit GH action
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z

#1019 [6.14.z] enabled the pre-commit CI and remove pre-commit GH action
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1020 [6.12.z] enabled the pre-commit CI and remove pre-commit GH action
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1018 New Host-Errata tab search fix
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1022 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  airgun/session.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1024 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  airgun/session.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1025 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  airgun/session.py
Labels: 6.12.z, No-CherryPick

#947 Pagination refactor
  airgun/views/acs.py
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
  airgun/views/cloud_insights.py
  airgun/views/filter.py
  airgun/views/host_new.py
  airgun/views/location.py
  airgun/views/task.py
  airgun/widgets.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#1035 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1034 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1033 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1031 [6.14.z] Pagination refactor
  airgun/views/acs.py
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
  airgun/views/cloud_insights.py
  airgun/views/filter.py
  airgun/views/host_new.py
  airgun/views/location.py
  airgun/views/task.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1036 [6.13.z] Pagination refactor
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
  airgun/views/cloud_insights.py
  airgun/views/filter.py
  airgun/views/host_new.py
  airgun/views/location.py
  airgun/views/task.py
  airgun/widgets.py
Labels: No-CherryPick, 6.13.z

#1037 [6.12.z] Pagination refactor
  airgun/views/ansible_role.py
  airgun/views/ansible_variable.py
  airgun/views/cloud_insights.py
  airgun/views/filter.py
  airgun/views/host_new.py
  airgun/views/location.py
  airgun/views/task.py
  airgun/widgets.py
Labels: 6.12.z, No-CherryPick

#1041 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1042 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1038 added the ui_sesion_id attribute for video-session
  airgun/session.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#1048 [6.15.z] - added the ui_sesion_id attribute for video-session (#1038)
  airgun/session.py
Labels: No-CherryPick

#1045 [6.12.z] added the ui_sesion_id attribute for video-session
  airgun/session.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1044 Changes for 6.15.z new branch
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1051 Fix navigation: All Hosts>Manage Columns
  airgun/views/host.py
Labels: CherryPick, 6.14.z, Stream, 6.15.z
