Repository SatelliteQE/airgun, pull requests merged in 2023-08, with the labels that each got.

#917 account_menu dropdown 'data-ouia-component-id' is changed now
  airgun/views/common.py
Labels: Automation failure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#918 [6.14.z] account_menu dropdown 'data-ouia-component-id' is changed now
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#919 Change entity routes to accomodate PF4 navigation with multiple levels
  airgun/entities/activationkey.py
  airgun/entities/ansible_role.py
  airgun/entities/ansible_variable.py
  airgun/entities/architecture.py
  airgun/entities/cloud_insights.py
  airgun/entities/cloud_inventory.py
  airgun/entities/config_report.py
  airgun/entities/containerimagetag.py
  airgun/entities/contentview_new.py
  airgun/entities/errata.py
  airgun/entities/hardware_model.py
  airgun/entities/job_template.py
  airgun/entities/lifecycleenvironment.py
  airgun/entities/media.py
  airgun/entities/modulestream.py
  airgun/entities/os.py
  airgun/entities/oscapcontent.py
  airgun/entities/oscappolicy.py
  airgun/entities/oscaptailoringfile.py
  airgun/entities/package.py
  airgun/entities/partitiontable.py
  airgun/entities/provisioning_template.py
  airgun/entities/report_template.py
  airgun/entities/sync_templates.py
  airgun/entities/task.py
  airgun/entities/webhook.py
Labels: No-CherryPick

#920 Change Hardware Model typo
  airgun/views/hardware_model.py
Labels: Automation failure, 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z

#913 update Search widgets to PF4 class
  airgun/views/ansible_variable.py
  airgun/views/architecture.py
  airgun/views/audit.py
  airgun/views/bookmark.py
  airgun/views/cloud_insights.py
  airgun/views/common.py
  airgun/views/computeprofile.py
  airgun/views/domain.py
  airgun/views/hardware_model.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/job_template.py
  airgun/views/location.py
  airgun/views/media.py
  airgun/views/modulestream.py
  airgun/views/organization.py
  airgun/views/os.py
  airgun/views/oscapcontent.py
  airgun/views/partitiontable.py
  airgun/views/provisioning_template.py
  airgun/views/report_template.py
  airgun/views/role.py
  airgun/views/settings.py
  airgun/views/task.py
  airgun/views/user.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#921 [6.13.z] Change Hardware Model typo
  airgun/views/hardware_model.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#926 [6.14.z] update Search widgets to PF4 class
  airgun/views/ansible_variable.py
  airgun/views/architecture.py
  airgun/views/audit.py
  airgun/views/bookmark.py
  airgun/views/cloud_insights.py
  airgun/views/common.py
  airgun/views/computeprofile.py
  airgun/views/domain.py
  airgun/views/hardware_model.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/job_template.py
  airgun/views/location.py
  airgun/views/media.py
  airgun/views/modulestream.py
  airgun/views/organization.py
  airgun/views/os.py
  airgun/views/oscapcontent.py
  airgun/views/partitiontable.py
  airgun/views/provisioning_template.py
  airgun/views/report_template.py
  airgun/views/role.py
  airgun/views/settings.py
  airgun/views/task.py
  airgun/views/user.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#914 Use PF4 Search in Webhooks
  airgun/views/webhook.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#928 [6.13.z] Use PF4 Search in Webhooks
  airgun/views/webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#929 [6.12.z] Use PF4 Search in Webhooks
  airgun/views/webhook.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#931 [6.13.z] update Search widgets to PF4 class (#913)
  airgun/views/ansible_variable.py
  airgun/views/architecture.py
  airgun/views/audit.py
  airgun/views/bookmark.py
  airgun/views/cloud_insights.py
  airgun/views/common.py
  airgun/views/computeprofile.py
  airgun/views/domain.py
  airgun/views/hardware_model.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/job_template.py
  airgun/views/location.py
  airgun/views/media.py
  airgun/views/modulestream.py
  airgun/views/organization.py
  airgun/views/os.py
  airgun/views/oscapcontent.py
  airgun/views/partitiontable.py
  airgun/views/provisioning_template.py
  airgun/views/report_template.py
  airgun/views/role.py
  airgun/views/settings.py
  airgun/views/task.py
  airgun/views/user.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: No-CherryPick

#932 [6.12.z] update Search widgets to PF4 class (#913)
  airgun/views/ansible_variable.py
  airgun/views/architecture.py
  airgun/views/audit.py
  airgun/views/bookmark.py
  airgun/views/cloud_insights.py
  airgun/views/common.py
  airgun/views/computeprofile.py
  airgun/views/domain.py
  airgun/views/hardware_model.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/job_template.py
  airgun/views/location.py
  airgun/views/media.py
  airgun/views/modulestream.py
  airgun/views/organization.py
  airgun/views/os.py
  airgun/views/oscapcontent.py
  airgun/views/partitiontable.py
  airgun/views/provisioning_template.py
  airgun/views/report_template.py
  airgun/views/role.py
  airgun/views/settings.py
  airgun/views/task.py
  airgun/views/user.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: No-CherryPick

#934 Add check for existence of title
  airgun/views/common.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z

#936 [6.14.z] Add check for existence of title
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#937 [6.13.z] Add check for existence of title
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#935 [6.12.z] Add check for existence of title
  airgun/views/common.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#930 Update puppet entity routes for PF4 navigation
  airgun/entities/configgroup.py
  airgun/entities/puppet_class.py
  airgun/entities/puppet_environment.py
  airgun/entities/smart_class_parameter.py
Labels: No-CherryPick

#940 Fix remediate method of CloudInsightsEntity
  airgun/entities/cloud_insights.py
Labels: 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z

#946 [6.14.z] Rework of virt card
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z
