Repository SatelliteQE/airgun, pull requests merged in 2023-06, with the labels that each got.

#850 Add Legacy content host UI support
  airgun/entities/contenthost.py
Labels: CherryPick, 6.13.z, 6.14.z

#854 fixed the cherry pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: 6.12.z, CherryPick, 6.11.z, 6.13.z, 6.14.z

#857 [6.14.z] fixed the cherry pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.14.z

#853 removing the unknown desired capability attributes
  airgun/browser.py
Labels: 6.12.z, CherryPick, 6.11.z, 6.13.z, 6.14.z

#862 [6.14.z] removing the unknown desired capability attributes
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#861 [6.13.z] removing the unknown desired capability attributes
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#859 [6.11.z] removing the unknown desired capability attributes
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.11.z

#860 [6.12.z] removing the unknown desired capability attributes
  airgun/browser.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#864 [6.14.z] add check virtwho config create&edit&delete flash message
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#866 Update Activation Keys OUIA ID
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#868 [6.14.z] Update Activation Keys OUIA ID
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#865 [RFE 6.13.z] Updating host views for 6.13.z
  airgun/views/host_new.py
Labels: enhancement, CherryPick, 6.13.z, 6.14.z

#869 Add Virtcard entity
  airgun/entities/computeresource.py
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, 6.14.z

#877 Bump GHA python version check to 3.10 and 3.11
  .github/workflows/pull_request.yml
  setup.py
Labels: enhancement, 6.12.z, CherryPick, 6.11.z, 6.13.z, 6.14.z

#880 [6.14.z] Bump GHA python version check to 3.10 and 3.11
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#881 [6.13.z] Bump GHA python version check to 3.10 and 3.11
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#878 [6.12.z] Bump GHA python version check to 3.10 and 3.11
  .github/workflows/pull_request.yml
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#879 [6.11.z] Bump GHA python version check to 3.10 and 3.11
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.11.z, AutoMerge_Cherry_Picked

#863 add orgnization option for virt-who configuration UI page
  airgun/views/virtwho_configure.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z
