Repository SatelliteQE/airgun, pull requests merged in 2023-07, with the labels that each got.

#882 [6.13.z] add orgnization option for virt-who configuration UI page
  airgun/views/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#884 [6.12.z] add orgnization option for virt-who configuration UI page
  airgun/views/virtwho_configure.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#883 [6.14.z] add orgnization option for virt-who configuration UI page
  airgun/views/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#871 [6.13.z] [RFE 6.13.z] Updating host views for 6.13.z
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#874 Added sleep to get_repos_set
  airgun/entities/host_new.py
Labels: critical, CherryPick, 6.13.z, 6.14.z

#870 Update Global Registration OUIA IDs
  airgun/views/host.py
Labels: No-CherryPick

#887 fix in audit log search
  airgun/views/audit.py
Labels: Automation failure, CherryPick, 6.14.z

#875 [6.14.z] Add Virtcard entity
  airgun/entities/computeresource.py
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#888 [6.14.z] fix in audit log search
  airgun/views/audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#852 [6.14 RFE] New Host and AK views and entities
  airgun/entities/activationkey.py
  airgun/entities/host_new.py
  airgun/views/activationkey.py
  airgun/views/host_new.py
Labels: enhancement, CherryPick, 6.14.z

#885 [6.13.z] Added sleep to get_repos_set
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#886 [6.14.z] Added sleep to get_repos_set
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#893 [6.14.z] Fixing organization and location locators
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#894 [6.14 RFE] [6.14.z] New Host and AK views and entities (#852)
  airgun/entities/activationkey.py
  airgun/entities/host_new.py
  airgun/views/activationkey.py
  airgun/views/host_new.py
Labels: enhancement, No-CherryPick, 6.14.z

#898 [6.14.z] remove g-chat notification for failed auto cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#900 [6.13.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#901 [6.12.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: 6.12.z, No-CherryPick

#902 [6.11.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.11.z

#903 current user dropdown updated
  airgun/views/common.py
Labels: Automation failure, CherryPick, 6.14.z

#905 [6.14.z] current user dropdown updated
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#904 Fix GR and current user OUIA ids
  airgun/views/host.py
Labels: No-CherryPick, 6.14.z

#907 [6.14.z] Add trigger-robottelo-workflow for updating robottelo image on quay
  .github/workflows/trigger_robottelo_workflow.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#908 [6.13.z] Add trigger-robottelo-workflow for updating robottelo image on quay
  .github/workflows/trigger_robottelo_workflow.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#910 [6.12.z] Add trigger-robottelo-workflow for updating robottelo image on quay
  .github/workflows/trigger_robottelo_workflow.yml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#876 Implementation of views and entities for new "Alternate Content Sources" page
  airgun/browser.py
  airgun/entities/acs.py
  airgun/session.py
  airgun/views/acs.py
  airgun/views/host_new.py
  airgun/widgets.py
Labels: enhancement, entity, view, CherryPick, 6.14.z

#911 [6.14.z] Implementation of views and entities for new "Alternate Content Sources" page
  airgun/browser.py
  airgun/entities/acs.py
  airgun/session.py
  airgun/views/acs.py
  airgun/views/host_new.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z
