Repository SatelliteQE/airgun, pull requests merged in 2024-11, with the labels that each got.

#1613 [6.16.z] Fix inconsistently failing Errata UI, checking New Host > Installed Packages > table
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1620 add read ansible role entities and views
  airgun/entities/ansible_role.py
  airgun/views/ansible_role.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1606 Fix locator for ACSes
  airgun/views/acs.py
Labels: locator, No-CherryPick, Stream, PRT-Passed

#1622 [6.16.z] add read ansible role entities and views
  airgun/entities/ansible_role.py
  airgun/views/ansible_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1625 [6.15.z] add read ansible role entities and views
  airgun/entities/ansible_role.py
  airgun/views/ansible_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1626 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1627 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1628 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1629 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1631 Add a couple of waits to RH repos pages
  airgun/entities/redhat_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1633 [6.14.z] Add a couple of waits to RH repos pages
  airgun/entities/redhat_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1634 [6.16.z] Add a couple of waits to RH repos pages
  airgun/entities/redhat_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1632 [6.15.z] Add a couple of waits to RH repos pages
  airgun/entities/redhat_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1603 hosts table: Name locator fix (again)
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1637 [6.16.z] hosts table: Name locator fix (again)
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1640 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1641 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1642 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1639 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1638 [6.15.z] hosts table: Name locator fix (again)
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1605 Add new Refresh button in capsule content
  airgun/entities/capsule.py
  airgun/views/capsule.py
Labels: No-CherryPick, Stream
