Repository SatelliteQE/airgun, pull requests merged in 2024-02, with the labels that each got.

#1225 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1222 [6.13.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1224 [6.14.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1223 [6.15.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1200 pf4 bookmarks dropdown
  airgun/views/capsule.py
  airgun/views/computeresource.py
  airgun/views/dashboard.py
  airgun/views/discoveryrule.py
  airgun/views/package.py
  airgun/views/repository.py
  airgun/views/subnet.py
  airgun/widgets.py
Labels: Automation failure, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1206 Adapt to additional div in taxonomy mismatch locator
  airgun/views/host.py
Labels: view, locator, CherryPick, 6.15.z

#1232 [6.15.z] Adapt to additional div in taxonomy mismatch locator
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1237 [6.15.z] Change content source cherry-pick
  airgun/entities/host.py
  airgun/entities/job_invocation.py
  airgun/views/host.py
  airgun/views/job_invocation.py
Labels: No-CherryPick

#1228 [6.15.z] pf4 bookmarks dropdown
  airgun/views/capsule.py
  airgun/views/computeresource.py
  airgun/views/dashboard.py
  airgun/views/discoveryrule.py
  airgun/views/package.py
  airgun/views/repository.py
  airgun/views/subnet.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1238 [6.14.z] Change content source cherry-pick
  airgun/entities/host.py
  airgun/entities/job_invocation.py
  airgun/views/host.py
  airgun/views/job_invocation.py
Labels: No-CherryPick

#1241 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1242 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1243 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1244 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1240 wait to display page in search_content_hosts()
  airgun/entities/errata.py
Labels: CherryPick, 6.14.z, Stream, 6.15.z

#1245 [6.15.z] wait to display page in search_content_hosts()
  airgun/entities/errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1246 [6.14.z] wait to display page in search_content_hosts()
  airgun/entities/errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1231 Fix hardware model delete functionality (6.15.z)
  airgun/entities/hardware_model.py
  airgun/views/hardware_model.py
Labels: CherryPick

#1234 [6.15.z] Navigation search: input clear fix
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1250 Navigation menu search: use proper PF4 button widget
  airgun/widgets.py
Labels: No-CherryPick

#1239 adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z, 6.15.z

#1029 Add debian repository to views
  airgun/views/repository.py
Labels: PRT-Failed

#1259 [6.13.z] adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1263 Fixing some views in job_invocation
  airgun/views/job_invocation.py
Labels: view, CherryPick, 6.14.z, 6.15.z

#1261 some more updated on PRT label checks
  .github/workflows/prt_labels.yml
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z, 6.15.z

#1266 Improve stability of before_fill function
  airgun/views/host.py
Labels: view, CherryPick, 6.14.z, 6.15.z

#1274 [6.14.z] Improve stability of before_fill function
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1273 [6.15.z] Improve stability of before_fill function
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z
