Repository SatelliteQE/airgun, pull requests merged in 2024-01, with the labels that each got.

#1098 Fix get_downloads_list which is causing save_downloaded_file to fail
  airgun/browser.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1096 virtwho config edit name message check update
  airgun/entities/virtwho_configure.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1113 fixing the auto-merge PR's in Airgun
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1100 [6.15.z] Fix get_downloads_list which is causing save_downloaded_file to fail
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1101 [6.14.z] Fix get_downloads_list which is causing save_downloaded_file to fail
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1102 [6.13.z] Fix get_downloads_list which is causing save_downloaded_file to fail
  airgun/browser.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1109 [6.14.z] virtwho config edit name message check update
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1111 [6.15.z] virtwho config edit name message check update
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1116 [6.15.z] fixing the auto-merge PR's in Airgun
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1114 [6.14.z] fixing the auto-merge PR's in Airgun
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1106 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1105 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1104 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1103 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1099 Correct capitalization
  airgun/views/job_invocation.py
Labels: CherryPick, 6.14.z, 6.15.z

#1118 [6.15.z] Correct capitalization
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1119 [6.14.z] Correct capitalization
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1121 Manual Cherrypick All Hosts UI to 6.15.z
  airgun/entities/all_hosts.py
  airgun/session.py
  airgun/views/all_hosts.py
Labels: No-CherryPick

#1123 moving sca alert into sub class
  airgun/entities/subscription.py
Labels: No-CherryPick, 6.15.z

#1120 Adding new functionality for multi repo override
  airgun/entities/host_new.py
Labels: CherryPick, 6.15.z

#1117 Add Dependabot Configuration YAML
  .github/dependabot.yml
Labels: No-CherryPick

#1126 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1124 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1125 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1148 [6.15.z] Bump mheap/github-action-required-labels from 2 to 5
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1146 [6.14.z] Bump mheap/github-action-required-labels from 2 to 5
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1145 [6.13.z] Bump mheap/github-action-required-labels from 2 to 5
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1147 [6.12.z] Bump mheap/github-action-required-labels from 2 to 5
  .github/workflows/required_labels.yml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1138 [6.14.z] Bump actions/setup-python from 2 to 5
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1140 [6.12.z] Bump actions/setup-python from 2 to 5
  .github/workflows/pull_request.yml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1137 [6.15.z] Bump actions/setup-python from 2 to 5
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1139 [6.13.z] Bump actions/setup-python from 2 to 5
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1127 [6.15.z] Adding new functionality for multi repo override
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1136 Bug 2158702:read virt-who config Edit view page info support
  airgun/entities/virtwho_configure.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1167 [6.12.z] Bump actions/github-script from 6 to 7
  .github/workflows/auto_cherry_pick.yml
Labels: 6.12.z, No-CherryPick, dependencies

#1168 [6.13.z] Bump actions/github-script from 6 to 7
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.13.z, dependencies

#1169 [6.14.z] Bump actions/github-script from 6 to 7
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.14.z, dependencies

#1170 [6.15.z] Bump actions/github-script from 6 to 7
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.15.z, dependencies

#1158 [6.13.z] Bug 2158702:read virt-who config Edit view page info support
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1159 [6.15.z] Bug 2158702:read virt-who config Edit view page info support
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1160 [6.14.z] Bug 2158702:read virt-who config Edit view page info support
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1163 [6.15.z] Bump actions/checkout from 2 to 4
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.15.z

#1166 [6.12.z] Bump actions/checkout from 2 to 4
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/pull_request.yml
Labels: 6.12.z, No-CherryPick

#1171 [6.13.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1172 [6.15.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1173 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1174 [6.14.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1176 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1177 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1178 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1184 [6.12.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: 6.12.z, No-CherryPick

#1185 [6.13.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.13.z

#1187 [6.15.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.15.z

#1186 [6.14.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.14.z

#1188 [6.14.z] Added possibility to search for debian errata
  airgun/__init__.py
  airgun/entities/errata.py
  airgun/views/errata.py
Labels: No-CherryPick, 6.14.z

#1189 [6.13.z] Added possibility to search for debian errata
  airgun/__init__.py
  airgun/entities/errata.py
  airgun/views/errata.py
Labels: No-CherryPick, 6.13.z

#1194 [6.14.z] Bump selenium from 4.11.2 to 4.16.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1193 [6.12.z] Bump selenium from 4.11.2 to 4.16.0
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1192 [6.15.z] Bump selenium from 4.11.2 to 4.16.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1191 [6.13.z] Bump selenium from 4.11.2 to 4.16.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1152 host_new>content>errata tab pagination
  airgun/entities/host_new.py
  airgun/views/host_new.py
  airgun/widgets.py
Labels: CherryPick, Stream, 6.15.z

#1202 [6.15.z] host_new>content>errata tab pagination
  airgun/entities/host_new.py
  airgun/views/host_new.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1199 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1203 SCAP content > SCAP contents
  airgun/views/oscapcontent.py
Labels: Automation failure, CherryPick, 6.15.z

#1205 [6.15.z] SCAP content > SCAP contents
  airgun/views/oscapcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1208 [6.14.z] Bump selenium from 4.16.0 to 4.17.2
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1211 [6.13.z] Bump selenium from 4.16.0 to 4.17.2
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1210 [6.15.z] Bump selenium from 4.16.0 to 4.17.2
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1213 [6.15.z] brought back task pagination
  airgun/views/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1215 [6.14.z] brought back task pagination
  airgun/views/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1214 [6.13.z] brought back task pagination
  airgun/views/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1212 [6.12.z] brought back task pagination
  airgun/views/task.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1216 Updated the correct context runner for Airgun
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick
