Repository SatelliteQE/airgun, pull requests merged in 2024-12, with the labels that each got.

#1650 [6.16.z] Template editor error widget
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1651 [6.14.z] Template editor error widget
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1411 add support for versions dropdown
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: CherryPick, 6.14.z, 6.15.z

#1663 [6.14.z] Bump selenium from 4.21.0 to 4.27.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1662 [6.15.z] Bump selenium from 4.21.0 to 4.27.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1660 [6.13.z] Bump selenium from 4.21.0 to 4.27.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1661 [6.16.z] Bump selenium from 4.21.0 to 4.27.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1664 [6.13.z] [pre-commit.ci] pre-commit autoupdate (#1645)
  .pre-commit-config.yaml
  airgun/views/contentviewfilter.py
  airgun/views/redhat_repository.py
  airgun/widgets.py
  pyproject.toml
Labels: No-CherryPick, 6.13.z, maintenance

#1665 [6.14.z] [pre-commit.ci] pre-commit autoupdate (#1645)
  .pre-commit-config.yaml
  airgun/views/contentviewfilter.py
  airgun/views/redhat_repository.py
  airgun/widgets.py
  pyproject.toml
Labels: No-CherryPick, 6.14.z, maintenance

#1668 Revert selenium bump and ignore it by dependabot.
  .github/dependabot.yml
  setup.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, dependencies, 6.16.z

#1675 Revert selenium dependency bump.
  setup.py
Labels: No-CherryPick, dependencies

#1673 Revert selenium dependency bump.
  setup.py
Labels: No-CherryPick, dependencies

#1670 [6.16.z] Revert selenium bump and ignore it by dependabot.
  .github/dependabot.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1677 Add leapp preupgrade remidiation view
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#1676 Cross check Airgun installation with robottelo's dependencies
  .github/workflows/pull_request.yml
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, maintenance, 6.16.z

#1683 [6.16.z] Cross check Airgun installation with robottelo's dependencies
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1682 [6.15.z] Cross check Airgun installation with robottelo's dependencies
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1681 [6.14.z] Cross check Airgun installation with robottelo's dependencies
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1680 [6.13.z] Cross check Airgun installation with robottelo's dependencies
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1679 [6.16.z] Add leapp preupgrade remidiation view
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1596 [6.16.z] add airgun support for parsing package details page link
  airgun/entities/package.py
  airgun/views/package.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z
