Repository SatelliteQE/airgun, pull requests merged in 2024-09, with the labels that each got.

#1537 [6.16.z] [6.16] Add support for the new ui button
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1524 [6.16.z] [6.16]Add support for CVE modal and PF4 version of LCE Selector
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
  airgun/views/common.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1544 Fix sattable locators
  airgun/widgets.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1545 [6.16.z] Fix sattable locators
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1546 [6.15.z] Fix sattable locators
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1547 override checkbox id updated in filters
  airgun/views/filter.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1543 validations with warnings too
  airgun/views/sync_templates.py
  airgun/widgets.py
Labels: CherryPick, 6.15.z, PRT-Passed, 6.16.z

#1542 adding ansible role as per given input...
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1549 [6.16.z] override checkbox id updated in filters
  airgun/views/filter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1548 [6.15.z] override checkbox id updated in filters
  airgun/views/filter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1550 [6.16.z] validations with warnings too
  airgun/views/sync_templates.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#1551 [6.15.z] validations with warnings too
  airgun/views/sync_templates.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#1558 [6.16.z] wait for task details to appear
  airgun/entities/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1559 [6.14.z] wait for task details to appear
  airgun/entities/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1556 wait for a dashboard card to load
  airgun/entities/dashboard.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1560 [6.16.z] wait for a dashboard card to load
  airgun/entities/dashboard.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1564 [6.15.z] Fix hostCollection entities
  airgun/entities/hostcollection.py
Labels: No-CherryPick, 6.15.z

#1565 [6.16.z] Fix hostCollection airgun entities
  airgun/entities/hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1566 Fix change assigned content entity
  airgun/entities/hostcollection.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1568 [6.15.z] Fix change assigned content entity
  airgun/entities/hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1522 Check dynflow console output for host
  airgun/entities/job_invocation.py
  airgun/views/dynflowconsole.py
  airgun/views/job_invocation.py
  airgun/views/task.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1553 [6.16.z] adding ansible role as per given input...
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1552 [6.15.z] adding ansible role as per given input...
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1554 [6.14.z] adding ansible role as per given input...
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1498 [6.15.z] Add ansible_collections_path in job invocation advanced_fields
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1529 [6.15.z] fixed in method for discovery rule and updated it's entities
  airgun/entities/discoveryrule.py
  airgun/views/discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1570 [6.16.z] Check dynflow console output for host
  airgun/entities/job_invocation.py
  airgun/views/dynflowconsole.py
  airgun/views/job_invocation.py
  airgun/views/task.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1576 [6.14z CP] Check dynflow console output for host
  airgun/entities/job_invocation.py
  airgun/views/dynflowconsole.py
  airgun/views/job_invocation.py
  airgun/views/task.py
Labels: No-CherryPick, 6.14.z

#1577 [6.15.z] Check dynflow console output for host
  airgun/entities/job_invocation.py
  airgun/views/dynflowconsole.py
  airgun/views/job_invocation.py
  airgun/views/task.py
Labels: CherryPick, 6.15.z, PRT-Passed
