Repository SatelliteQE/airgun, pull requests merged in 2024-07, with the labels that each got.

#1453 hosts table: Name locator fix
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1446 [6.15.z] Update get_host_facts to read a nested value
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1444 [6.14.z] Update get_host_facts to read a nested value
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1455 Add pagination for ansible_roles in HostGroupEditView
  airgun/views/hostgroup.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1459 [6.15.z] Add pagination for ansible_roles in HostGroupEditView
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1458 [6.14.z] Add pagination for ansible_roles in HostGroupEditView
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1461 removed (.) which fails to navigate to host
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1462 Update Infrastructure-Virt-who Configurations navigator name
  airgun/entities/virtwho_configure.py
Labels: No-CherryPick

#1445 [6.13.z] Update get_host_facts to read a nested value
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1465 ignore all hidden columns in SatTable widget
  airgun/widgets.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1448 Fix race condition in PF4 progressbar
  airgun/widgets.py
Labels: CherryPick, 6.15.z

#1468 [6.15.z] ignore all hidden columns in SatTable widget
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1471 Add support of new widget on Host Register page for adding multiple repositories
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, Stream, PRT-Passed

#1439 Locator added in host view
  airgun/views/computeresource.py
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1476 making auto-merge should be same as master
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick

#1474 [6.15.z] Locator added in host view
  airgun/views/computeresource.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1477 making auto-merge should be same as master
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick

#1473 [6.14.z] Locator added in host view
  airgun/views/computeresource.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1475 Revert removal of taxonomy from host module
  airgun/views/host.py
Labels: No-CherryPick, Easy Fix :)

#1481 Update activation key dropdown locator on Hostgroup create page
  airgun/views/hostgroup.py
Labels: No-CherryPick, Stream, PRT-Passed
