Repository SatelliteQE/airgun, pull requests merged in 2024-08, with the labels that each got.

#1426 Add support for File page in Content section of UI
  airgun/entities/file.py
  airgun/session.py
  airgun/views/file.py
Labels: CherryPick, 6.14.z, 6.15.z

#1487 [6.16] Adjust all hosts to use menu, add support for Build Management
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
Labels: No-CherryPick, Stream

#1484 [6.15.z] Add support for File page in Content section of UI
  airgun/entities/file.py
  airgun/session.py
  airgun/views/file.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1486 Remove cpu_mode option from host and compute_profile view
  airgun/views/computeresource.py
  airgun/views/host.py
Labels: No-CherryPick, Stream

#1479 changes to fetch the config report data
  airgun/entities/activationkey.py
  airgun/entities/host_new.py
  airgun/views/activationkey.py
  airgun/views/host_new.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1490 [6.14.z] changes to fetch the config report data
  airgun/entities/activationkey.py
  airgun/entities/host_new.py
  airgun/views/activationkey.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1494 Table locator updated to get value from "Provisioning Templates" table
  airgun/views/provisioning_template.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, Easy Fix :)

#1496 [6.15.z] Table locator updated to get value from "Provisioning Templates" table
  airgun/views/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1495 [6.14.z] Table locator updated to get value from "Provisioning Templates" table
  airgun/views/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1463 Add ansible_collections_path in job invocation advanced_fields
  airgun/views/job_invocation.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, Easy Fix :)

#1482 Cherry pick 6.15.z 1661b6ce61639d4465bdbd24b37f4bde889d5ce0
  airgun/widgets.py
Labels: No-CherryPick

#1492 [6.15.z] changes to fetch the config report data
  airgun/entities/activationkey.py
  airgun/entities/host_new.py
  airgun/views/activationkey.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1504 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1502 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1503 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1500 Fix ruff deprecation warnings
  pyproject.toml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, maintenance

#1510 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick

#1509 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick

#1508 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick

#1506 [6.15.z] Fix ruff deprecation warnings
  pyproject.toml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1505 [6.14.z] Fix ruff deprecation warnings
  pyproject.toml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1507 [6.13.z] Fix ruff deprecation warnings
  pyproject.toml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1499 Locator updated in is_supported() method...
  airgun/entities/provisioning_template.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1512 [6.15.z] Locator updated in is_supported() method...
  airgun/entities/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1511 [6.14.z] Locator updated in is_supported() method...
  airgun/entities/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1521 [6.16.z]: Changes for 6.16.z new branch
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1517 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1514 [6.16]Add support for CVE modal and PF4 version of LCE Selector
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
  airgun/views/common.py
  airgun/widgets.py
Labels: CherryPick, Stream, 6.16.z

#1515 New job invocation details page
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: No-CherryPick

#1528 [6.13z cp] Table locator updated to get value from "Provisioning Templates" table
  airgun/views/provisioning_template.py
Labels: No-CherryPick, 6.13.z, PRT-Passed

#1480 fixed in method for discovery rule and updated it's entities
  airgun/entities/discoveryrule.py
  airgun/views/discoveryrule.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#1530 [6.16.z] fixed in method for discovery rule and updated it's entities
  airgun/entities/discoveryrule.py
  airgun/views/discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1533 [6.16.z] New job invocation details page
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#1441 SCAP report and remediation
  airgun/entities/oscapreport.py
  airgun/session.py
  airgun/views/common.py
  airgun/views/oscapreport.py
  airgun/widgets.py
Labels: No-CherryPick, PRT-Passed

#1526 [6.16] All Hosts Manage Errata
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
Labels: CherryPick, 6.16.z

#1536 [6.16] Add support for the new ui button
  airgun/entities/host.py
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z
