Repository SatelliteQE/airgun, pull requests merged in 2024-10, with the labels that each got.

#1541 [6.16.z] [Comp Eval] Add installability to generate views
  airgun/views/report_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1540 [6.15.z] [Comp Eval] Add installability to generate views
  airgun/views/report_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1578 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1579 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1580 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1581 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1585 [6.16.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.16.z

#1583 [6.14.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1587 [6.15.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4 (#1575)
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.15.z

#1588 [6.13.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4 (#1575)
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.13.z

#1589 Add entity that reads filled searchbox on new and old hosts pages
  airgun/entities/all_hosts.py
  airgun/entities/host.py
Labels: entity, CherryPick, 6.16.z

#1593 add airgun support for parsing package details page link
  airgun/entities/package.py
  airgun/views/package.py
Labels: CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, Stream, 6.16.z

#939 CV UI - Promote, Publish, Add Content
  airgun/entities/contentview_new.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#1600 [6.16.z] CV UI - Promote, Publish, Add Content
  airgun/entities/contentview_new.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1534 [6.13.z] added changes in host_new entities
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, 6.13.z, PRT-Failed

#1592 New CV UI - ContentView and ContentViewVersion Delete
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: CherryPick, Stream, PRT-Passed, 6.16.z

#1604 [6.16.z] New CV UI - ContentView and ContentViewVersion Delete
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1607 update ansible variable matcher_value locator
  airgun/views/ansible_variable.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, Easy Fix :), 6.16.z

#1610 [6.14.z] update ansible variable matcher_value locator
  airgun/views/ansible_variable.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1609 [6.15.z] update ansible variable matcher_value locator
  airgun/views/ansible_variable.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1608 [6.16.z] update ansible variable matcher_value locator
  airgun/views/ansible_variable.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1612 Fix inconsistently failing Errata UI, checking New Host > Installed Packages > table
  airgun/entities/host_new.py
Labels: CherryPick, Stream, 6.15.z, 6.16.z

#1615 Add reclaim_space_warning node to the capsule view
  airgun/views/capsule.py
Labels: view, CherryPick, 6.16.z

#1617 [6.16.z] Add reclaim_space_warning node to the capsule view
  airgun/views/capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1611 Add support for getting documentation related urls from Satellite page
  airgun/entities/about.py
  airgun/entities/fact_value.py
  airgun/entities/global_parameter.py
  airgun/session.py
  airgun/views/about.py
  airgun/views/common.py
  airgun/views/global_parameter.py
Labels: CherryPick, Stream, 6.16.z

#1618 [6.16.z] Add support for getting documentation related urls from Satellite page
  airgun/entities/about.py
  airgun/entities/fact_value.py
  airgun/entities/global_parameter.py
  airgun/session.py
  airgun/views/about.py
  airgun/views/common.py
  airgun/views/global_parameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z
