Repository SatelliteQE/airgun, pull requests merged in 2024-05, with the labels that each got.

#1374 Add fetching of all errata entries from new host page, fix search of errata on legacy chost page
  airgun/entities/contenthost.py
  airgun/entities/host_new.py
Labels: CherryPick, Stream, 6.15.z

#1375 [6.15.z] Add fetching of all errata entries from new host page, fix search of errata on legacy chost page
  airgun/entities/contenthost.py
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1372 Add pagination from ansible_roles tab in hostgroup create view
  airgun/views/hostgroup.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, Easy Fix :)

#1379 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1380 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1381 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1382 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1378 [6.13.z] Add pagination from ansible_roles tab in hostgroup create view
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked, PRT-Passed

#1348 [6.15.z] added changes in host_new entities
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1384 Basic host statuses page
  airgun/entities/host.py
  airgun/views/host.py
Labels: CherryPick, 6.15.z

#1377 [6.15.z] Add pagination from ansible_roles tab in hostgroup create view
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1391 fixing make-docs issue with some update in code
  airgun/entities/subscription.py
  airgun/helpers/base.py
  airgun/widgets.py
Labels: 6.12.z, CherryPick, 6.13.z, 6.14.z, 6.15.z

#1395 [6.15.z] fixing make-docs issue with some update in code
  airgun/entities/subscription.py
  airgun/helpers/base.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1392 [6.14.z] fixing make-docs issue with some update in code
  airgun/entities/subscription.py
  airgun/helpers/base.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1393 [6.13.z] fixing make-docs issue with some update in code
  airgun/entities/subscription.py
  airgun/helpers/base.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1394 [6.12.z] fixing make-docs issue with some update in code
  airgun/entities/subscription.py
  airgun/helpers/base.py
  airgun/widgets.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1385 added new support for feature manifest expires soon
  airgun/entities/subscription.py
  airgun/views/subscription.py
Labels: No-CherryPick, Stream, do not merge

#1390 browser teardown fix at session exit
  airgun/session.py
Labels: 6.12.z, CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1396 [6.12.z] browser teardown fix at session exit
  airgun/session.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1397 Enable root_password in discovered_host_edit_view
  airgun/entities/discoveredhosts.py
  airgun/views/host.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, Easy Fix :)

#1399 [6.14.z] Enable root_password in discovered_host_edit_view
  airgun/entities/discoveredhosts.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1402 [6.13.z] Bump selenium from 4.19.0 to 4.21.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1401 [6.12.z] Bump selenium from 4.19.0 to 4.21.0
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#1403 [6.15.z] Bump selenium from 4.19.0 to 4.21.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1404 [6.14.z] Bump selenium from 4.19.0 to 4.21.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1398 [6.15.z] Enable root_password in discovered_host_edit_view
  airgun/entities/discoveredhosts.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z
