Repository SatelliteQE/airgun, pull requests merged in 2024-04, with the labels that each got.

#1307 [6.12.z] Bump selenium from 4.18.1 to 4.19.0
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, PRT-Failed

#1305 [6.13.z] Bump selenium from 4.18.1 to 4.19.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Failed

#1306 [6.15.z] Bump selenium from 4.18.1 to 4.19.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#1308 [6.14.z] Bump selenium from 4.18.1 to 4.19.0
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed

#1299 Rework is_displayed logic for contenthost
  airgun/entities/contenthost.py
Labels: CherryPick, 6.15.z

#1300 add/update host_new entities & views
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1313 [6.15.z] add/update host_new entities & views
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1314 [6.14.z] add/update host_new entities & views
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1315 redhat_repositories search box & button xpath, add wait_for in search
  airgun/entities/redhat_repository.py
  airgun/views/redhat_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed

#1291 addition of auto-branching process as part of github action
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#1320 [6.15.z] Fixes in repo discovery and search
  airgun/views/product.py
  airgun/views/repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1318 [6.14.z] Fixes in repo discovery and search
  airgun/views/product.py
  airgun/views/repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1319 [6.13.z] Fixes in repo discovery and search
  airgun/views/product.py
  airgun/views/repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1312 Update TOTP field locator
  airgun/views/rhsso_login.py
Labels: CherryPick, 6.15.z

#1325 added properties for airgun
  airgun/entities/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1326 [6.14.z] added properties for airgun
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1327 [6.15.z] added properties for airgun
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1347 added changes in host_new entities
  airgun/entities/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1349 [6.14.z] added changes in host_new entities
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1337 Added entity that returns counts of the errata types
  airgun/entities/host_new.py
Labels: entity, CherryPick, 6.13.z, 6.14.z, 6.15.z

#1354 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  airgun/browser.py
  airgun/exceptions.py
  airgun/fixtures.py
  airgun/navigation.py
  airgun/session.py
  docs/conf.py
Labels: No-CherryPick, 6.15.z

#1355 [6.14.z] pre-commit cherry-pick and formatting changes
  .pre-commit-config.yaml
  airgun/browser.py
  airgun/exceptions.py
  airgun/fixtures.py
  airgun/navigation.py
  airgun/session.py
  docs/conf.py
Labels: No-CherryPick, 6.14.z

#1356 [6.13.z] pre-commit bumps and formatting changes
  .pre-commit-config.yaml
  airgun/browser.py
  airgun/exceptions.py
  airgun/fixtures.py
  airgun/navigation.py
  airgun/session.py
  docs/conf.py
Labels: No-CherryPick, 6.13.z

#1357 [6.12.z] pre-commit bumps and formatting changes
  .pre-commit-config.yaml
  airgun/browser.py
  airgun/exceptions.py
  airgun/fixtures.py
  airgun/navigation.py
  airgun/session.py
  docs/conf.py
Labels: 6.12.z, No-CherryPick

#1360 [6.15.z] Added entity that returns counts of the errata types
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1362 edit host view wait until displayed
  airgun/entities/host.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1365 [6.14.z] edit host view wait until displayed
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1364 [6.13.z] edit host view wait until displayed
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1366 [6.15.z] edit host view wait until displayed
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1367 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1369 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1368 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1370 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked
