Repository SatelliteQE/airgun, pull requests merged in 2024-06, with the labels that each got.

#1083 CV UI - Add versions screen, and capability to search/read all tables
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1405 6.15.z-fix subscription search box xpath
  airgun/entities/subscription.py
  airgun/views/subscription.py
Labels: Automation failure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1412 [6.14.z] 6.15.z-fix subscription search box xpath
  airgun/entities/subscription.py
  airgun/views/subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1413 [6.15.z] browser teardown fix at session exit
  airgun/session.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.16.z

#1415 [6.14.z] browser teardown fix at session exit
  airgun/session.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1414 [6.13.z] browser teardown fix at session exit
  airgun/session.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1407 [6.16.z]: Changes for 6.16.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1406 [master]: Changes for 6.16.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#1388 [6.15.z] Basic host statuses page
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1316 added properties for hostgroup
  airgun/entities/host_new.py
  airgun/entities/hostgroup.py
  airgun/views/host_new.py
  airgun/views/hostgroup.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1418 [6.14.z] added properties for hostgroup
  airgun/entities/host_new.py
  airgun/entities/hostgroup.py
  airgun/views/host_new.py
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1419 [6.15.z] added properties for hostgroup
  airgun/entities/host_new.py
  airgun/entities/hostgroup.py
  airgun/views/host_new.py
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1389 contenthost legacy ui get virtual host support
  airgun/views/contenthost.py
Labels: CherryPick, 6.14.z, 6.15.z, Easy Fix :)

#1420 6.14.z changes - increse timeout for read subscription
  airgun/entities/subscription.py
  airgun/views/subscription.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1422 [6.14.z] contenthost legacy ui get virtual host support
  airgun/views/contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1423 [6.15.z] contenthost legacy ui get virtual host support
  airgun/views/contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1421 Manage columns support for All Hosts
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
Labels: No-CherryPick, Stream

#1387 Errata install, and legacy chost methods
  airgun/entities/contenthost.py
  airgun/entities/errata.py
  airgun/entities/host_new.py
  airgun/views/errata.py
  airgun/views/host_new.py
Labels: CherryPick, Stream, 6.15.z, PRT-Passed

#1425 Removing outdating views for hostcontent sca tests
  airgun/views/contenthost.py
Labels: enhancement, No-CherryPick, Stream

#1432 [6.15.z] adding and removing ansible role
  airgun/entities/hostgroup.py
  airgun/views/hostgroup.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1433 [6.14.z] adding and removing ansible role
  airgun/entities/hostgroup.py
  airgun/views/hostgroup.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1427 Add Facts View and add function to read host facts
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1434 [6.14.z] Add Facts View and add function to read host facts
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1435 [6.15.z] Add Facts View and add function to read host facts
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1436 [6.13.z] Add Facts View and add function to read host facts
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1431 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1429 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1430 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1440 Fix OUID for rex_pull_mode in host registration
  airgun/views/host.py
Labels: No-CherryPick, Stream, PRT-Passed, Easy Fix :)

#1428 [6.15.z] Errata install, and legacy chost methods
  airgun/entities/contenthost.py
  airgun/entities/errata.py
  airgun/entities/host_new.py
  airgun/views/errata.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1437 Update get_host_facts to read a nested value
  airgun/entities/host_new.py
  airgun/views/fact.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1443 Manifest expiration date appearance of header and message
  airgun/entities/subscription.py
Labels: No-CherryPick, Stream

#1449 PR checks for python 3.12
  .github/workflows/pull_request.yml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1451 [6.15.z] PR checks for python 3.12
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1452 [6.14.z] PR checks for python 3.12
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1450 [6.13.z] PR checks for python 3.12
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z
