Repository SatelliteQE/airgun, pull requests merged in 2024-03, with the labels that each got.

#1272 [6.13] pf4 bookmarks dropdown
  airgun/views/computeresource.py
  airgun/views/dashboard.py
  airgun/views/discoveryrule.py
  airgun/views/package.py
  airgun/views/repository.py
  airgun/views/subnet.py
  airgun/widgets.py
Labels: No-CherryPick, 6.13.z

#1271 [6.14] pf4 bookmarks dropdown
  airgun/views/computeresource.py
  airgun/views/dashboard.py
  airgun/views/discoveryrule.py
  airgun/views/package.py
  airgun/views/repository.py
  airgun/views/subnet.py
  airgun/widgets.py
Labels: No-CherryPick, 6.14.z

#1264 [6.14.z] Fixing some views in job_invocation
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1265 [6.15.z] Fixing some views in job_invocation
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1262 Rex targetting
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: No-CherryPick

#1267 [6.15.z] some more updated on PRT label checks
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1268 [6.14.z] some more updated on PRT label checks
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1270 [6.13.z] some more updated on PRT label checks
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1277 [6.15.z] Bump selenium from 4.17.2 to 4.18.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1276 [6.13.z] Bump selenium from 4.17.2 to 4.18.1
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1279 [6.12.z] Bump selenium from 4.17.2 to 4.18.1
  setup.py
Labels: 6.12.z, No-CherryPick, Auto_Cherry_Picked

#1283 [CP] Add debian repository to views
  airgun/views/repository.py
Labels: No-CherryPick, 6.15.z

#1281 Check that breadcrumb is displayed
  airgun/entities/contenthost.py
Labels: CherryPick, 6.15.z

#1293 [6.14] Update get_register_command to reflect new mandatory fields (#1087)
  airgun/entities/host.py
Labels: No-CherryPick, 6.14.z

#1280 Wait for toast/flash message to be visible
  airgun/entities/hardware_model.py
Labels: CherryPick, 6.15.z

#1295 Fixes needed for some Endeavour tests to run correctly
  airgun/entities/host.py
  airgun/entities/host_new.py
  airgun/entities/job_invocation.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1296 [6.14.z] Fixes needed for some Endeavour tests to run correctly
  airgun/entities/host.py
  airgun/entities/host_new.py
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1297 [6.15.z] Fixes needed for some Endeavour tests to run correctly
  airgun/entities/host.py
  airgun/entities/host_new.py
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1294 [6.15.z] Wait for toast/flash message to be visible
  airgun/entities/hardware_model.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z
