Repository SatelliteQE/airgun, pull requests merged in 2025-10, with the labels that each got.

#2118 PF4 to PF5 conversion of dialog windows
  airgun/views/host_new.py
Labels: view, CherryPick, Stream, PRT-Passed, 6.18.z

#1995 job invocation details: hosts table fix
  airgun/views/job_invocation.py
Labels: CherryPick, PRT-Passed, 6.18.z

#2041 Add_provision_method_check_for_Libvirt
  airgun/views/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#2113 [6.18.z] Add New changes to read hosts if new UI is available
  airgun/entities/discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#2130 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#2128 [6.18.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z
