Repository SatelliteQE/airgun, pull requests merged in 2025-01, with the labels that each got.

#1643 removing updated value and takes default value
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#1694 [6.14.z] check links in EOL banner
  airgun/entities/eol_banner.py
  airgun/views/eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1693 [6.15.z] check links in EOL banner
  airgun/entities/eol_banner.py
  airgun/views/eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1691 [6.16.z] check links in EOL banner
  airgun/entities/eol_banner.py
  airgun/views/eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1621 Proxy support for template sync
  airgun/views/sync_templates.py
Labels: No-CherryPick

#1695 Update fill method logic for button values
  airgun/widgets.py
Labels: PF4, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, Easy Fix :), 6.16.z

#1685 Switch Airgun CI/CQ to uv
  .github/workflows/pull_request.yml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, maintenance, 6.16.z

#1704 [6.13.z] Switch Airgun CI/CQ to uv
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1705 [6.15.z] Switch Airgun CI/CQ to uv
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1706 [6.14.z] Switch Airgun CI/CQ to uv
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1707 [6.16.z] Switch Airgun CI/CQ to uv
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1702 subscription page search field ui selector update
  airgun/views/subscription.py
Labels: CherryPick, Stream, PRT-Passed, 6.16.z

#1701 updated read func which will read the value and click on submit.
  airgun/entities/hostgroup.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, Stream, 6.15.z, PRT-Passed, Easy Fix :), 6.16.z

#1708 Extend sync_status page with active_only support
  airgun/entities/sync_status.py
  airgun/views/sync_status.py
Labels: CherryPick, 6.16.z

#1717 [6.16.z] updated read func which will read the value and click on submit.
  airgun/entities/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1718 [6.14.z] updated read func which will read the value and click on submit.
  airgun/entities/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1720 [6.16.z] Extend sync_status page with active_only support
  airgun/entities/sync_status.py
  airgun/views/sync_status.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1712 [6.16.z] Bump astral-sh/setup-uv from 4 to 5
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.16.z

#1716 [6.13.z] Bump astral-sh/setup-uv from 4 to 5
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.13.z
