Repository SatelliteQE/airgun, pull requests merged in 2025-05, with the labels that each got.

#1822 Update Capsule with PF5
  airgun/entities/capsule.py
  airgun/views/capsule.py
Labels: No-CherryPick, Stream

#1839 CloudInventory Fixes
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_inventory.py
Labels: No-CherryPick, Stream, PRT-Passed

#1843 Tracer Fixes and new entity
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1848 Fix Manifest Alert View PF4->PF5
  airgun/views/subscription.py
Labels: No-CherryPick, Stream, PRT-Passed

#1837 [RFE] Add functionality for minimal data collection report
  airgun/views/cloud_inventory.py
Labels: No-CherryPick, Stream

#1847 fix CVE Reassign PF4->PF5
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed

#1845 Add upgrade entity
  airgun/entities/upgrade.py
  airgun/session.py
  airgun/views/common.py
  airgun/views/upgrade.py
Labels: No-CherryPick, Stream

#1849 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1852 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1850 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1790 update locator due to change of pf5
  airgun/views/host.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed, Easy Fix :)

#1763 Add multi promote support to publish/promote entity
  airgun/entities/contentview_new.py
Labels: entity, CherryPick, 6.16.z, 6.17.z

#1855 [6.17.z] Add multi promote support to publish/promote entity
  airgun/entities/contentview_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1854 [6.16.z] Add multi promote support to publish/promote entity
  airgun/entities/contentview_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1857 [PF5] MenuToggleDropdownInTable
  airgun/views/all_hosts.py
Labels: No-CherryPick, Stream, PRT-Passed

#1846 Add view and entities for Flatpak Remotes
  airgun/entities/flatpak.py
  airgun/session.py
  airgun/views/flatpak.py
Labels: No-CherryPick, Stream

#1858 Update ACS with PF5
  airgun/entities/acs.py
  airgun/views/acs.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed

#1860 CloudInventory UI Test Fix
  airgun/entities/cloud_inventory.py
Labels: No-CherryPick, 6.16.z

#1861 content views PF5 updates
  airgun/entities/contentview_new.py
  airgun/views/common.py
  airgun/views/contentview_new.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed

#1859 Fix navigation for Job Templates
  airgun/entities/job_template.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Failed, 6.17.z
