Repository SatelliteQE/airgun, pull requests merged in 2025-02, with the labels that each got.

#1703 Add Python 3.13 for PR checks in GHA
  .github/workflows/pull_request.yml
  setup.py
Labels: CherryPick, Framework Changes, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#1729 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1722 Move "Insights" navigation menu items from under "Configure"
  airgun/entities/cloud_insights.py
  airgun/entities/cloud_inventory.py
Labels: No-CherryPick, Stream, PRT-Passed

#1721 Add support to invalidate users JSON Web Tokens
  airgun/entities/user.py
  airgun/views/user.py
Labels: No-CherryPick, Stream

#1709 [6.16.z] subscription page search field ui selector update
  airgun/views/subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#1736 Parametrize the Python version in PR workflow
  .github/workflows/pull_request.yml
Labels: No-CherryPick

#1732 [6.15.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1731 [6.16.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1738 update FilteredDropdown locator in widgets
  airgun/views/computeresource.py
  airgun/views/host.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed, Easy Fix :)

#1636 Add locator for content_default_http_proxy checkbox on HTTP proxy create page
  airgun/entities/http_proxy.py
  airgun/views/http_proxy.py
Labels: No-CherryPick, Stream

#1743 RFE: added widgets for the new job invocation page
  airgun/views/job_invocation.py
  airgun/widgets.py
Labels: No-CherryPick, Stream

#1744 Add AK update host limit entity
  airgun/entities/activationkey.py
  airgun/views/activationkey.py
Labels: entity, view, No-CherryPick, Stream

#1746 Auto branching: Add randomness to branch name
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#1747 [master]: Changes for 6.17.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#1748 [6.17.z]: Changes for 6.17.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1745 Add view/entity for booted container images page
  airgun/entities/bootc.py
  airgun/session.py
  airgun/views/bootc.py
Labels: CherryPick, 6.17.z

#1751 Change TemplateInputItem
  airgun/views/common.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#1753 [6.17.z] Change TemplateInputItem
  airgun/views/common.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z
