Repository SatelliteQE/airgun, pull requests merged in 2025-08, with the labels that each got.

#1951 [6.17.z] Pre-Commit CP Fix
  .pre-commit-config.yaml
  airgun/widgets.py
Labels: No-CherryPick, 6.17.z

#1946 More Robust Navigation To All Hosts
  airgun/entities/all_hosts.py
Labels: No-CherryPick, Stream, PRT-Passed

#1955 Fix LegacyDetails navigation
  airgun/entities/contenthost.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Failed, 6.16.z, 6.17.z

#1949 [6.17.z] update alert msg after host delete
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1924 Extend flatpak view and entity with remote details page
  airgun/entities/flatpak.py
  airgun/views/flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#1941 PF5 updates for host detail Content: Errata & Module streams tabs
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1963 Fixed All Hosts page edit functionality to support patternfly5 changes
  airgun/entities/host.py
  airgun/views/host.py
Labels: No-CherryPick, Stream, PRT-Passed

#1938 PF5 migration of Bookmarks
  airgun/views/common.py
Labels: No-CherryPick, PRT-Failed

#1919 Add entities/views updates for transient-install
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
  airgun/views/host_new.py
  airgun/views/oscapreport.py
Labels: No-CherryPick, Stream

#1973 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1982 Update for PF5 and test EditorModal
  airgun/views/common.py
  airgun/views/partitiontable.py
Labels: No-CherryPick, Stream

#1981 Add in entities and views to accommodate test cases based on image for…
  airgun/entities/computeresource.py
  airgun/views/computeresource.py
Labels: CherryPick, Stream

#1987 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1994 Update Insights HostDetails Tab
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1993 cherrypick : Add in entities and views to accommodate test cases based…
  airgun/entities/computeresource.py
  airgun/views/computeresource.py
Labels: CherryPick, 6.17.z

#1990 Cherrypick : Add in entities and views to accommodate test cases based…
  airgun/entities/computeresource.py
  airgun/views/computeresource.py
Labels: No-CherryPick, 6.15.z
