Repository SatelliteQE/airgun, pull requests merged in 2025-04, with the labels that each got.

#1784 [6.17.z] users: Last login time column added
  airgun/views/user.py
Labels: No-CherryPick, PRT-Passed

#1785 Update host details bootc card to use proper locator
  airgun/views/host_new.py
Labels: view, CherryPick, 6.17.z

#1786 [6.17.z] Update host details bootc card to use proper locator
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1787 Extend http proxy with Test Connection button
  airgun/entities/http_proxy.py
  airgun/views/http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#1791 [6.17.z] Extend http proxy with Test Connection button
  airgun/entities/http_proxy.py
  airgun/views/http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1795 Fix_ChangeContentSource
  airgun/entities/job_invocation.py
  airgun/views/host.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, Stream, PRT-Passed

#1796 Alert Fix PF4 to PF5
  airgun/entities/all_hosts.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed

#1797 Lowercase HTTP proxy
  airgun/entities/product.py
  airgun/views/product.py
  airgun/views/repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#1798 [6.17.z] Lowercase HTTP proxy
  airgun/entities/product.py
  airgun/views/product.py
  airgun/views/repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1792 Insights patternfly 5 updates
  airgun/views/cloud_insights.py
  airgun/views/common.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1800 Add helper entites for RH inventory
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_inventory.py
Labels: No-CherryPick, Stream

#1801 wait_to_success_job_task
  airgun/entities/job_invocation.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, Stream, 6.15.z, Easy Fix :), 6.16.z, 6.17.z

#1804 [6.17.z] wait_to_success_job_task
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1803 [6.16.z] wait_to_success_job_task
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1805 [6.15.z] wait_to_success_job_task
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1802 [6.14.z] wait_to_success_job_task
  airgun/entities/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1816 Fix ManageColumns View PF4->PF5
  airgun/views/all_hosts.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream, PRT-Passed

#1817 pf5 related adjustments for rex
  airgun/entities/job_invocation.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, Stream, PRT-Passed

#1812 confirm modal for PF5
  airgun/browser.py
  airgun/widgets.py
Labels: No-CherryPick, PRT-Passed

#1821 Get displayed Inventory tabs entity
  airgun/entities/cloud_inventory.py
Labels: No-CherryPick, Stream, PRT-Passed

#1819 hostgroups: PF5 update & navigation improvements
  airgun/entities/hostgroup.py
  airgun/views/hostgroup.py
Labels: No-CherryPick, PRT-Passed

#1826 [6.17.z] pre-commit upgrade
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.17.z

#1823 [6.14.z] pre-commit upgrade
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.14.z

#1824 [6.15.z] pre-commit upgrade
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.15.z

#1825 [6.16.z] pre-commit upgrade
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.16.z

#1827 user info dropdown to PF5
  airgun/views/common.py
Labels: No-CherryPick, Stream, PRT-Passed
