Repository SatelliteQE/airgun, pull requests merged in 2025-09, with the labels that each got.

#1999 [master]: Changes for 6.18.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#2001 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#2017 [6.17.z] Sync dependencies with the master branch
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.17.z

#2016 [6.18.z] Sync dependencies with the master branch
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, 6.18.z

#2014 [6.18.z] Bump actions/setup-python from 5 to 6
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.18.z

#2023 [6.18.z] Host Group view extension
  airgun/views/hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#2025 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#2026 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#2020 [6.18.z] Added refresh as job status for perticular hosts is not getting updated by itself
  airgun/entities/contenthost.py
  airgun/views/job_invocation.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#2037 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#2038 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#2036 [6.18.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#2043 [6.18.z] Fixed NewHostDetailsView -> overview to read details correctly
  airgun/views/hardware_model.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#1978 Add view/entities for Hosts->vulnerabilities tab and vulnerability list page
  airgun/entities/cloud_vulnerabilities.py
  airgun/entities/host_new.py
  airgun/session.py
  airgun/views/cloud_vulnerabilities.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#2033 [6.18.z] Add view/entities for Hosts->vulnerabilities tab and vulnerability list page
  airgun/entities/cloud_vulnerabilities.py
  airgun/entities/host_new.py
  airgun/session.py
  airgun/views/cloud_vulnerabilities.py
  airgun/views/host_new.py
Labels: No-CherryPick, 6.18.z

#2060 Fix host status locator which was broken due to earlier changes
  airgun/views/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#2061 Slightly rework pagination widget to work
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, PRT-Passed, 6.18.z

#2058 Add upper bound for Patternfly libraries #1
  setup.py
Labels: CherryPick, Stream, 6.18.z

#2055 [6.17.z] limit widgetastic core version
  setup.py
Labels: No-CherryPick, 6.17.z

#2056 [6.16.z] limit widgetastic core version
  setup.py
Labels: No-CherryPick, 6.16.z

#2049 read recommended repositories by it types
  airgun/entities/redhat_repository.py
  airgun/views/redhat_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.17.z, 6.18.z

#2059 [6.17.z] Add upper bound for patternfly libs
  setup.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#2071 [6.15.z] AddUpperBoundForPatternflyLibs
  setup.py
Labels: No-CherryPick, 6.15.z

#2075 [6.17.z] Bump lewagon/wait-on-check-action from 1.4.0 to 1.4.1
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, 6.17.z

#2074 [6.15.z] Bump lewagon/wait-on-check-action from 1.4.0 to 1.4.1
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#2079 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.16.z

#2072 [6.18.z] Bump lewagon/wait-on-check-action from 1.4.0 to 1.4.1
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#2081 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.17.z

#2092 [6.18.z] Drop Black and use just Ruff & Single Quotes Rule Added for Ruff
  .pre-commit-config.yaml
  airgun/entities/contentview.py
  airgun/entities/contentviewfilter.py
  airgun/entities/host.py
  airgun/views/capsule.py
  airgun/views/cloud_inventory.py
  airgun/views/hostcollection.py
  airgun/views/job_invocation.py
  airgun/views/subscription.py
  airgun/widgets.py
  pyproject.toml
Labels: No-CherryPick, maintenance, 6.18.z

#2091 [6.17.z] Drop Black and use just Ruff & Single Quotes Rule Added for Ruff
  .pre-commit-config.yaml
  airgun/entities/contentview.py
  airgun/entities/contentviewfilter.py
  airgun/entities/host.py
  airgun/views/acs.py
  airgun/views/capsule.py
  airgun/views/hostcollection.py
  airgun/views/subscription.py
  airgun/widgets.py
  pyproject.toml
Labels: No-CherryPick, maintenance, 6.17.z

#2087 [6.17.z] Make job invocation view more stable as PRT was failng
  airgun/entities/contenthost.py
Labels: No-CherryPick, 6.17.z

#2099 [6.16.z] Bump actions/setup-python from 5 to 6
  .github/workflows/pull_request.yml
Labels: No-CherryPick, 6.16.z

#2106 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#2107 [6.18.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#2094 Add New changes to read hosts if new UI is available
  airgun/entities/discoveryrule.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.18.z

#2114 more stable get_packages
  airgun/entities/host_new.py
Labels: CherryPick, Stream, PRT-Passed, 6.18.z
