Repository SatelliteQE/airgun, pull requests merged in 2025-06, with the labels that each got.

#1864 Add dialog view to cloud inventory
  airgun/views/cloud_inventory.py
Labels: locator, No-CherryPick, Stream, PRT-Passed

#1862 [6.17.z] Fix navigation for Job Templates
  airgun/entities/job_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1867 Remove 6.14.z from dependabot PR labels
  .github/dependabot.yml
Labels: No-CherryPick, maintenance

#1869 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1841 updates to new host views
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1865 Fix external usergroup locator
  airgun/views/usergroup.py
Labels: CherryPick, 6.17.z

#1877 update host detail page locator
  airgun/views/host_new.py
Labels: No-CherryPick, Stream, PRT-Passed

#1882 remove rhev functionality
  airgun/entities/computeresource.py
  airgun/entities/virtwho_configure.py
  airgun/views/computeresource.py
  airgun/views/host.py
  airgun/views/virtwho_configure.py
Labels: No-CherryPick, Stream

#1880 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1844 update locator and pf5 changes
  airgun/views/ansible_role.py
  airgun/views/computeresource.py
  airgun/widgets.py
Labels: No-CherryPick, Stream

#1884 PF5 Locators. Host > Content tabs. searchbars, dropdowns
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1863 fixed PF5 select locator for host group/activation keys
  airgun/views/host.py
  airgun/views/hostgroup.py
Labels: No-CherryPick, PRT-Passed

#1885 vertical menu search: fixed PF5 button locators
  airgun/views/common.py
  airgun/widgets.py
Labels: No-CherryPick, Stream, PRT-Passed

#1893 [6.17.z] waiting for alert message after host delete
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#1895 [6.16.z] fix: broken techdocs annotations
  catalog-info.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1896 [6.17.z] fix: broken techdocs annotations
  catalog-info.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1904 [6.16.z] Bump lewagon/wait-on-check-action from 1.3.4 to 1.4.0
  .github/workflows/auto_cherry_pick_merge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1901 Update locators to PF5 for DiscoveryPlugin
  airgun/views/host_new.py
Labels: No-CherryPick, Stream, PRT-Passed
