Repository SatelliteQE/airgun, pull requests merged in 2025-03, with the labels that each got.

#1750 remove s2id from the locator
  airgun/views/capsule.py
  airgun/views/computeresource.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/oscappolicy.py
  airgun/views/partitiontable.py
  airgun/views/report_template.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#1754 [6.17.z] remove s2id from the locator
  airgun/views/capsule.py
  airgun/views/computeresource.py
  airgun/views/host.py
  airgun/views/hostgroup.py
  airgun/views/oscappolicy.py
  airgun/views/partitiontable.py
  airgun/views/report_template.py
  airgun/views/usergroup.py
  airgun/widgets.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#1755 fix TemplatesList locator to fetch value
  airgun/views/os.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, Easy Fix :), 6.17.z

#1756 [6.17.z] fix TemplatesList locator to fetch value
  airgun/views/os.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#1752 [6.17.z] Add view/entity for booted container images page
  airgun/entities/bootc.py
  airgun/session.py
  airgun/views/bootc.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1700 [6.16.z] Add support for viewing the needs_publish banner in the cv index page…
  airgun/entities/contentview_new.py
  airgun/views/contentview_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1758 Remove Python 3.10 support
  .github/workflows/pull_request.yml
  setup.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z, 6.17.z

#1759 [6.17.z] Remove Python 3.10 support
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1760 [6.15.z] Remove Python 3.10 support
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1767 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1766 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  airgun/entities/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1757 Add entity to run bootc REX jobs, and add view for bootc card
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: CherryPick, 6.17.z

#1770 JIRA issues is fixed, removing workaround
  airgun/entities/bootc.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#1769 [6.17.z] Add entity to run bootc REX jobs, and add view for bootc card
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1782 [6.17.z] Fixing the timing to ensure smooth host creation.
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#1781 [6.16.z] Fixing the timing to ensure smooth host creation.
  airgun/entities/host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#1783 users: Last login time column added
  airgun/views/user.py
Labels: No-CherryPick
