Repository SatelliteQE/airgun, pull requests merged in 2025-07, with the labels that each got.

#1911 Fix class name typo
  airgun/views/host_new.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, Easy Fix :), 6.16.z, 6.17.z

#1916 [6.16.z Cherrypick] Fix class name typo (#1911)
  airgun/views/host_new.py
Labels: No-CherryPick, 6.16.z

#1917 [6.15.z Cherrypick] Fix class name typo (#1911)
  airgun/views/host_new.py
Labels: No-CherryPick, 6.15.z

#1909 Disassociate Hosts Coverage [SAT-31029]
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
Labels: entity, view, No-CherryPick, Stream

#1900 update alert msg after host delete
  airgun/entities/host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#1925 host Status View Update
  airgun/views/host_new.py
Labels: view, No-CherryPick, PRT-Passed, Easy Fix :)

#1734 Fix ContentView view
  airgun/entities/contentview_new.py
  airgun/views/common.py
  airgun/views/contentview_new.py
Labels: No-CherryPick, PRT-Passed

#1930 hosts Content/Packages fixes
  airgun/entities/host_new.py
  airgun/views/common.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream

#1933 Change Owner/Org/Loc entities/views coverage
  airgun/entities/all_hosts.py
  airgun/views/all_hosts.py
Labels: entity, view, No-CherryPick, Stream

#1928 Update insights to lightspeed select and locators
  airgun/entities/cloud_insights.py
  airgun/entities/cloud_inventory.py
  airgun/views/cloud_insights.py
  airgun/views/cloud_inventory.py
  airgun/views/host.py
Labels: No-CherryPick, Stream

#1932 [Test Fixes] Revert search_field locators to include multiple cases
  airgun/widgets.py
Labels: locator, No-CherryPick, Stream, PRT-Failed

#1935 All Hosts legacy UI navigation fix
  airgun/entities/host.py
  airgun/entities/host_new.py
  airgun/views/host_new.py
Labels: No-CherryPick, Stream, PRT-Passed
